
variables:
  solution: 'RxUI.MauiToolkit/RxUI.MauiToolkit.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  TOOLKIT_NET6_VERSION: '6.0.300'
  LATEST_NET6_VERSION: '6.0.x'


trigger:
  branches:
    include:
    - main
    - develop
pr:
  autoCancel: 'true'
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - README.md

jobs:
  - job: build_windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Windows-build'
        publishLocation: 'Container'
