
variables:
  solution: 'RxUI.MauiToolkit/RxUI.MauiToolkit.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  TOOLKIT_NET6_VERSION: '6.0.300'
  LATEST_NET6_VERSION: '6.0.x'


trigger:
  branches:
    include:
    - main
    - develop
pr:
  autoCancel: 'true'
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - README.md

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    # - task: VSBuild@1
    #   inputs:
    #     solution: '$(solution)'
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'
    
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          ${env:BUILD_BUILDNUMBER}++

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**\bin\release\**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # - task: VSTest@2
    #   inputs:
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Builds'
        publishLocation: 'Container'
